### PR TITLE
Bump nodejs10.x to 10.17.0

### PR DESCRIPTION
**Pull request by styfle**
*Description of changes:* Bump `nodejs10.x` to version 10.17.0

### CODE REVIEW

**Comment by mwunderl** [comment]
Thanks! We're working on a process to keep this information up-to-date. I'll remove the version numbers until we can ensure that it stays correct.

**Comment by styfle** [comment]
@mwunderl That would be great if this information was updated automatically.

I would be _even better_ the data was available in json or some other machine readable format.

Would that be possible?

**Comment by mwunderl** [comment]
I completely agree and would love to see all runtime details available from the runtime itself or from the Lambda API. I'll pass your feedback on to the engineering team.

**Comment by styfle** [comment]
Wonderful! Thanks you 🙏

**Pull request merged**
