### PR TITLE
Add note how to use AML2 for custom runtimes.

### PR DESCRIPTION
**Pull request by rustyconover**
Add a note about how to opt into Amazon Linux 2 for Lambda custom runtimes.

*Issue #, if available:* 

*Description of changes:*

Just add additional documentation.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mwunderl** [comment]
Hi Rusty,

I'm not familiar with that layer. I'll check with the engineering team.

Thanks,
-Michael at AWS

**Comment by rustyconover** [comment]
Any luck?

**Comment by mwunderl** [comment]
Hi Rusty,

The layer does exist but is not officially supported at this time. When we have more information on AL2 for custom runtimes I will note it in the guide's [releases page](https://docs.aws.amazon.com/lambda/latest/dg/lambda-releases.html), and there will probably be a blog post as well.

Thanks,
-Michael

**Comment by styfle** [comment]
Hi @mwunderl 

I am also trying to get a `provided` runtime to use AL2 so I'm curious what the correct solution is. 

I'm going to try this out to see if it works but if its not official then that could cause problems in the future.

@rustyconover Is `arn:aws:lambda:::awslayer:AmazonLinux2` a literal string or is the region (and other parts) missing?

**Comment by rustyconover** [comment]
@styfle That's the literal string.  Just copy and paste it as a layer ARN.

**Comment by styfle** [comment]
@rustyconover Great, it worked! I tried to download it to see the contents but it said the arn was invalid so this must be a special string.

One thing I noticed is that it works when I use `runtime: provided` but not `runtime: ruby2.5` or `runtime: go1.x` (which are both using AL1, not AL2 as far as I can tell).

**Comment by rustyconover** [comment]
I've only tested it with my own provided runtimes that I've built on AL2.

**Comment by styfle** [comment]
I've noticed that using the layer `arn:aws:lambda:::awslayer:AmazonLinux2` results in an error:

```
arn:aws:lambda:::awslayer:AmazonLinux2 is not a valid execution environment
```

However this is only affecting `eu-central-1`. For example, `us-west-1` still works.

Can we keep this layer working until this is an alternative announced? cc @jfuss @mwunderl

**Comment by jfuss** [comment]
From https://github.com/awslabs/aws-sam-cli/issues/1890#issuecomment-608032966:

Thanks for the request. The arn:aws:lambda:::awslayer:AmazonLinux2 layer is not an officially supported layer. This was enabled for testing purposes by Lambda itself. Lambda will provide the relevant customer communication and details on timelines after which this layer will be disabled.

**Pull request closed without merging**
