### PR TITLE
Clean up example code, add links to new notes.

### PR DESCRIPTION
**Pull request by ryapric**
*Issue #, if available:*
None.

*Description of changes:*
The example Python Deployment Package code used a gratuitous amount of relative path changes in the code blocks. These have been eliminated in favor of all operations being performed from the repository top-level, and all example code dependent on the previous format has been cleaned up accordingly. All examples still behave as originally described, when run interactively.

I have also added a few new `Note` fields to some entries, covering a possible `pip` error and the existence of Python 3's native `venv` module vs. `virtualenv`.

Thanks!

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by HashedDan** [comment]
Improves readability and is a cleaner way of writing code. Thanks @ryapric !

**Comment by ryapric** [comment]
Having now used the previous suggested changes in end-to-end practice, I now see that the way `zip` handles its paths is not conducive to idiomatic Python module discovery (i.e. it zips & names everything relative to the current directory, with no options to change this behavior). I have mostly reset the path conventions, but instead of dot-relative references, I have taken advantage of the `$OLDPWD` environment variable. This still results in less-cluttered and cleaner code.

**Comment by mwunderl** [comment]
Hi Ryan,
Thanks for your feedback. Why say "actual" function code?

**Comment by ryapric** [comment]
Hi Michael,

I was just trying to be clear that the file being added in that step was the Lambda Function code itself, and not something else that could be construed as "function code". But on second look, I suppose it doesn't really matter, and I can remove that if you'd prefer!

**Comment by mwunderl** [comment]
I removed it. Thanks for your contribution!

**Pull request merged**
